#!/usr/bin/env python3
"""
CESTOF automatic CZ + SK + DE + HU radar COMPOSITE-only generator.

What it does:
- Checks CHMI, SHMU, DWD, and Hungarian MET open-data radar directories
- Finds the newest CZ timestamp with nearby SK/DE/HU files
- Downloads CZ MAXZ, SK ZMAX, DE DMAX, and HU refl2D
- Reprojects everything to EPSG:3857
- Merges by maximum dBZ
- Exports sharp transparent PNG radar frames for Leaflet
- Updates radar/radar_index.json for the website time slider
- Repeats every 25 seconds
- Composite only: no individual radar site overlays

Install:
    pip install h5py numpy rasterio pyproj matplotlib beautifulsoup4 requests xarray netCDF4

Run:
    python cestof_auto_radar_hu.py

Then open from another terminal:
    cd radar
    python -m http.server 8000

Open your website radar.html page after uploading the radar folder.
"""

import json
import re
import time
import shutil
import warnings
from pathlib import Path
from datetime import datetime, timezone
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

import h5py
import numpy as np
import rasterio
from rasterio import Affine
from rasterio.crs import CRS
from rasterio.merge import merge
from rasterio.warp import calculate_default_transform, reproject, Resampling
from pyproj import CRS as PyprojCRS
from pyproj import Transformer, Geod

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, BoundaryNorm


# =========================
# SETTINGS
# =========================

CHMI_MAXZ_BASE = "https://opendata.chmi.cz/meteorology/weather/radar/composite/maxz/hdf5/"
SHMU_ZMAX_BASE = "https://opendata.shmu.sk/meteorology/weather/radar/composite/skcomp/zmax/"
DWD_DMAX_BASE = "https://opendata.dwd.de/weather/radar/composite/dmax/"
HU_REFL2D_BASE = "https://odp.met.hu/weather/radar/composite/nc/refl2D/"

# The website uses only the merged composite overlay.
# No individual radar-site/product catalog is generated by this version.

OUT_DIR = Path("radar")
CACHE_DIR = Path("radar_downloads")
FRAME_DIR = OUT_DIR / "radar_frames"

INTERVAL_SECONDS = 25
MAX_FRAMES_ON_HTML_SLIDER = 24
TARGET_EPSG = 3857
TARGET_RESOLUTION_METERS = 1000
MAX_TIME_DIFF_SECONDS = 10 * 60

# If Hungarian listing or NetCDF parsing fails, keep running with CZ/SK/DE only.
HU_OPTIONAL = True

USER_AGENT = "CESTOF-radar-auto/1.1"


# =========================
# BASIC HELPERS
# =========================

def ensure_dirs():
    OUT_DIR.mkdir(exist_ok=True)
    CACHE_DIR.mkdir(exist_ok=True)
    FRAME_DIR.mkdir(exist_ok=True)


def http_get_text(url, verify=True):
    r = requests.get(url, timeout=45, headers={"User-Agent": USER_AGENT}, verify=verify)
    r.raise_for_status()
    # Some directory listings have weird encodings; replace invalid characters.
    r.encoding = r.encoding or "utf-8"
    return r.text


def http_download(url, out_path, verify=True):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if out_path.exists() and out_path.stat().st_size > 0:
        return out_path

    print(f"Downloading: {url}")
    with requests.get(url, timeout=120, headers={"User-Agent": USER_AGENT}, verify=verify, stream=True) as r:
        r.raise_for_status()
        tmp = out_path.with_suffix(out_path.suffix + ".part")
        with open(tmp, "wb") as f:
            for chunk in r.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    f.write(chunk)
        tmp.replace(out_path)

    return out_path


def parse_listing_links(url, verify=True):
    html = http_get_text(url, verify=verify)
    soup = BeautifulSoup(html, "html.parser")
    links = []
    for a in soup.find_all("a"):
        href = a.get("href")
        if href:
            links.append(href)
    return links

def ts_to_iso(ts):
    dt = datetime.strptime(ts, "%Y%m%d%H%M%S").replace(tzinfo=timezone.utc)
    return dt.isoformat().replace("+00:00", "Z")


def ts_to_epoch(ts):
    dt = datetime.strptime(ts, "%Y%m%d%H%M%S").replace(tzinfo=timezone.utc)
    return int(dt.timestamp())


def nearest_timestamp(target_ts, available_ts, max_diff_seconds=MAX_TIME_DIFF_SECONDS):
    if not available_ts:
        return None
    target = ts_to_epoch(target_ts)
    best = min(available_ts, key=lambda t: abs(ts_to_epoch(t) - target))
    if abs(ts_to_epoch(best) - target) <= max_diff_seconds:
        return best
    return None


def extract_timestamp_from_any_filename(name):
    """
    Accept many patterns:
    20260510175000
    20260510_1750
    2026-05-10_17-50
    """
    s = str(name)

    m = re.search(r"(20\d{6})(\d{6})", s)
    if m:
        return m.group(1) + m.group(2)

    m = re.search(r"(20\d{6})[_-]?(\d{4})(?!\d)", s)
    if m:
        return m.group(1) + m.group(2) + "00"

    m = re.search(r"(20\d{2})[-_]?(\d{2})[-_]?(\d{2}).*?(\d{2})[-_]?(\d{2})(?:[-_]?(\d{2}))?", s)
    if m:
        return "".join(m.groups(default="00"))

    return None


# =========================
# SOURCE LISTING
# =========================

def list_chmi_timestamps():
    links = parse_listing_links(CHMI_MAXZ_BASE, verify=True)
    out = []
    for href in links:
        m = re.search(r"T_PABV23_C_OKPR_(\d{14})\.hdf", href)
        if m:
            out.append(m.group(1))
    return sorted(set(out))


def list_dwd_timestamps():
    links = parse_listing_links(DWD_DMAX_BASE, verify=True)
    out = []
    for href in links:
        m = re.search(r"composite_dmax_(\d{8})_(\d{4})-hd5", href)
        if m:
            out.append(m.group(1) + m.group(2) + "00")
    return sorted(set(out))


def list_shmu_timestamps_for_date(date_yyyymmdd):
    url = f"{SHMU_ZMAX_BASE}{date_yyyymmdd}/"
    try:
        links = parse_listing_links(url, verify=False)
    except Exception as e:
        print(f"SHMU listing failed for {date_yyyymmdd}: {e}")
        return []

    out = []
    for href in links:
        m = re.search(r"T_PABV22_C_LZIB_(\d{14})\.hdf", href)
        if m:
            out.append(m.group(1))
    return sorted(set(out))


def list_hu_files():
    """
    Hungarian MET refl2D NetCDF directory.
    This uses a broad parser because file naming may differ.
    Returns dict: timestamp -> href
    """
    try:
        links = parse_listing_links(HU_REFL2D_BASE, verify=False)
    except Exception as e:
        print(f"Hungarian MET listing failed: {e}")
        return {}

    out = {}
    for href in links:
        low = href.lower()
        if not (low.endswith(".nc") or low.endswith(".nc4") or low.endswith(".cdf") or ".nc?" in low or "refl" in low):
            continue
        ts = extract_timestamp_from_any_filename(href)
        if ts:
            out[ts] = href
    return dict(sorted(out.items()))


def find_latest_frame_set():
    cz_times = list_chmi_timestamps()
    de_times = list_dwd_timestamps()
    hu_files = list_hu_files()

    if not cz_times:
        raise RuntimeError("No CHMI timestamps found.")
    if not de_times:
        raise RuntimeError("No DWD timestamps found.")

    for cz_ts in reversed(cz_times[-80:]):
        date = cz_ts[:8]
        sk_times = list_shmu_timestamps_for_date(date)
        sk_ts = nearest_timestamp(cz_ts, sk_times)
        de_ts = nearest_timestamp(cz_ts, de_times)
        hu_ts = nearest_timestamp(cz_ts, list(hu_files.keys())) if hu_files else None

        if sk_ts and de_ts and (hu_ts or HU_OPTIONAL):
            return {
                "main_ts": cz_ts,
                "cz_ts": cz_ts,
                "sk_ts": sk_ts,
                "de_ts": de_ts,
                "hu_ts": hu_ts,
                "hu_href": hu_files.get(hu_ts) if hu_ts else None,
                "iso": ts_to_iso(cz_ts)
            }

    raise RuntimeError("Could not find matching CZ/SK/DE/HU radar times.")


def source_url(kind, ts, href=None):
    date = ts[:8]
    if kind == "cz":
        fn = f"T_PABV23_C_OKPR_{ts}.hdf"
        return CHMI_MAXZ_BASE + fn, fn
    if kind == "sk":
        fn = f"T_PABV22_C_LZIB_{ts}.hdf"
        return f"{SHMU_ZMAX_BASE}{date}/{fn}", fn
    if kind == "de":
        fn = f"composite_dmax_{ts[:8]}_{ts[8:12]}-hd5"
        return DWD_DMAX_BASE + fn, fn
    if kind == "hu":
        if not href:
            raise ValueError("HU source needs href from listing.")
        url = urljoin(HU_REFL2D_BASE, href)
        fn = href.rstrip("/").split("/")[-1]
        return url, fn
    raise ValueError(kind)


def download_source(kind, ts, href=None):
    url, fn = source_url(kind, ts, href=href)
    verify = False if kind in ("sk", "hu") else True
    return http_download(url, CACHE_DIR / fn, verify=verify)


# =========================
# HDF5 / ODIM READING
# =========================

def _decode_attr(v):
    if isinstance(v, bytes):
        return v.decode("utf-8", errors="ignore")
    if isinstance(v, np.ndarray) and v.shape == ():
        return v.item()
    if isinstance(v, np.generic):
        return v.item()
    return v


def attrs_dict(obj):
    return {k: _decode_attr(v) for k, v in obj.attrs.items()}


def find_first_2d_dataset(h5):
    preferred = [
        "/dataset1/data1/data",
        "dataset1/data1/data",
        "/dataset1/data2/data",
        "dataset1/data2/data",
    ]
    for p in preferred:
        if p in h5 and isinstance(h5[p], h5py.Dataset) and h5[p].ndim == 2:
            return p

    candidates = []
    def visitor(name, obj):
        if isinstance(obj, h5py.Dataset) and obj.ndim == 2:
            score = 0
            if name.lower().endswith("/data") or name.lower() == "data":
                score += 10
            if "dataset1" in name.lower():
                score += 3
            if "data1" in name.lower():
                score += 2
            candidates.append((score, name))
    h5.visititems(visitor)

    if not candidates:
        raise RuntimeError("No 2D dataset found in HDF5 file.")
    candidates.sort(reverse=True)
    return candidates[0][1]


def get_group_attrs_upwards(h5, dataset_path):
    groups = ["/", "/what", "/where", "/how"]

    parts = dataset_path.strip("/").split("/")
    if len(parts) >= 1:
        groups += ["/" + parts[0], "/" + parts[0] + "/what", "/" + parts[0] + "/where", "/" + parts[0] + "/how"]
    if len(parts) >= 2:
        g = "/" + "/".join(parts[:2])
        groups += [g, g + "/what", g + "/where", g + "/how"]

    meta = {}
    for g in groups:
        if g in h5:
            for k, v in attrs_dict(h5[g]).items():
                meta[k] = v

    for k, v in attrs_dict(h5[dataset_path]).items():
        meta[k] = v

    return meta


def read_odim_hdf_raster(path):
    path = Path(path)

    with h5py.File(path, "r") as h5:
        dset_path = find_first_2d_dataset(h5)
        raw = h5[dset_path][:]
        meta = get_group_attrs_upwards(h5, dset_path)

        data_group = "/" + "/".join(dset_path.strip("/").split("/")[:-1])
        data_meta = {}
        if data_group in h5:
            data_meta.update(attrs_dict(h5[data_group]))
        if data_group + "/what" in h5:
            data_meta.update(attrs_dict(h5[data_group + "/what"]))

        gain = float(data_meta.get("gain", meta.get("gain", 1.0)))
        offset = float(data_meta.get("offset", meta.get("offset", 0.0)))
        nodata = data_meta.get("nodata", meta.get("nodata", None))
        undetect = data_meta.get("undetect", meta.get("undetect", None))

        arr = raw.astype("float32")
        mask = np.zeros(arr.shape, dtype=bool)

        if nodata is not None:
            try:
                mask |= raw == float(nodata)
            except Exception:
                pass
        if undetect is not None:
            try:
                mask |= raw == float(undetect)
            except Exception:
                pass

        arr = arr * gain + offset
        arr[mask] = np.nan

        projdef = meta.get("projdef", None)
        if projdef:
            src_crs = CRS.from_string(str(projdef))
            py_src = PyprojCRS.from_user_input(str(projdef))
        else:
            warnings.warn(f"No projdef found in {path.name}. Falling back to EPSG:4326.")
            src_crs = CRS.from_epsg(4326)
            py_src = PyprojCRS.from_epsg(4326)

        corner_keys = ["LL_lon", "LL_lat", "UL_lon", "UL_lat", "UR_lon", "UR_lat", "LR_lon", "LR_lat"]
        has_corners = all(k in meta for k in corner_keys)

        height, width = arr.shape

        if has_corners:
            ll = (float(meta["LL_lon"]), float(meta["LL_lat"]))
            ul = (float(meta["UL_lon"]), float(meta["UL_lat"]))
            ur = (float(meta["UR_lon"]), float(meta["UR_lat"]))
            lr = (float(meta["LR_lon"]), float(meta["LR_lat"]))

            transformer = Transformer.from_crs("EPSG:4326", py_src, always_xy=True)
            xs, ys = transformer.transform(
                [ll[0], ul[0], ur[0], lr[0]],
                [ll[1], ul[1], ur[1], lr[1]],
            )

            left = min(xs)
            right = max(xs)
            bottom = min(ys)
            top = max(ys)

            px_w = (right - left) / width
            px_h = (top - bottom) / height
            transform = Affine(px_w, 0, left, 0, -px_h, top)

        else:
            xscale = float(meta.get("xscale", meta.get("XScale", 1000.0)))
            yscale = float(meta.get("yscale", meta.get("YScale", 1000.0)))

            if "LL_lon" in meta and "LL_lat" in meta:
                transformer = Transformer.from_crs("EPSG:4326", py_src, always_xy=True)
                left, bottom = transformer.transform(float(meta["LL_lon"]), float(meta["LL_lat"]))
                top = bottom + height * yscale
                transform = Affine(xscale, 0, left, 0, -yscale, top)
            else:
                raise RuntimeError(f"Could not georeference {path.name}. Missing corner metadata.")

        return arr, src_crs, transform


def read_hu_netcdf_raster(path):
    """
    Read Hungarian MET refl2D NetCDF.
    This tries common NetCDF layouts:
    - data variable with lon/lat 1D coordinates
    - data variable with 2D lon/lat coordinates
    - projected x/y coordinates with CRS attrs
    """
    try:
        import xarray as xr
    except Exception as e:
        raise RuntimeError("Hungarian NetCDF support needs xarray + netCDF4: pip install xarray netCDF4") from e

    ds = xr.open_dataset(path)

    # Pick likely reflectivity variable.
    preferred_names = ["refl2D", "refl", "reflectivity", "DBZH", "dbzh", "data", "radar"]
    data_var = None

    for name in preferred_names:
        if name in ds.data_vars:
            data_var = ds[name]
            break

    if data_var is None:
        candidates = []
        for name, da in ds.data_vars.items():
            if len(da.shape) >= 2 and np.issubdtype(da.dtype, np.number):
                score = 0
                low = name.lower()
                if "refl" in low or "dbz" in low or "dbzh" in low:
                    score += 10
                candidates.append((score, name, da))
        if not candidates:
            raise RuntimeError(f"No usable 2D numeric NetCDF variable found in {path}")
        candidates.sort(reverse=True)
        data_var = candidates[0][2]

    # Remove time/level dimensions by taking latest/first.
    da = data_var
    while da.ndim > 2:
        da = da.isel({da.dims[0]: -1})

    arr = np.array(da.values, dtype="float32")

    # Apply scale/offset if xarray did not decode for some reason.
    fill_values = []
    for key in ["_FillValue", "missing_value"]:
        if key in data_var.attrs:
            try:
                fill_values.append(float(data_var.attrs[key]))
            except Exception:
                pass
    for fv in fill_values:
        arr[arr == fv] = np.nan

    # Try to find lon/lat coordinate names.
    lon_names = ["lon", "longitude", "xlon", "longitudes"]
    lat_names = ["lat", "latitude", "xlat", "latitudes"]

    lon = None
    lat = None
    for n in lon_names:
        if n in ds.coords:
            lon = ds[n]
            break
        if n in ds:
            lon = ds[n]
            break
    for n in lat_names:
        if n in ds.coords:
            lat = ds[n]
            break
        if n in ds:
            lat = ds[n]
            break

    if lon is not None and lat is not None:
        lonv = np.array(lon.values)
        latv = np.array(lat.values)

        # 1D regular lon/lat grid.
        if lonv.ndim == 1 and latv.ndim == 1:
            # Make sure y order matches array.
            west = float(np.nanmin(lonv))
            east = float(np.nanmax(lonv))
            south = float(np.nanmin(latv))
            north = float(np.nanmax(latv))

            h, w = arr.shape
            transform = Affine((east - west) / w, 0, west, 0, -(north - south) / h, north)
            return arr, CRS.from_epsg(4326), transform

        # 2D lon/lat grid; approximate as rectified bounds.
        if lonv.ndim == 2 and latv.ndim == 2:
            west = float(np.nanmin(lonv))
            east = float(np.nanmax(lonv))
            south = float(np.nanmin(latv))
            north = float(np.nanmax(latv))

            h, w = arr.shape
            transform = Affine((east - west) / w, 0, west, 0, -(north - south) / h, north)
            return arr, CRS.from_epsg(4326), transform

    # Try projected x/y coords.
    x = None
    y = None
    for n in ["x", "X", "easting", "projection_x_coordinate"]:
        if n in ds.coords:
            x = ds[n]
            break
    for n in ["y", "Y", "northing", "projection_y_coordinate"]:
        if n in ds.coords:
            y = ds[n]
            break

    if x is not None and y is not None:
        xv = np.array(x.values, dtype="float64")
        yv = np.array(y.values, dtype="float64")
        west = float(np.nanmin(xv))
        east = float(np.nanmax(xv))
        south = float(np.nanmin(yv))
        north = float(np.nanmax(yv))

        h, w = arr.shape
        transform = Affine((east - west) / w, 0, west, 0, -(north - south) / h, north)

        # Try CRS from common attrs; fallback to EPSG:4326 is bad but explicit.
        crs = None
        for var in ds.variables.values():
            attrs = getattr(var, "attrs", {})
            for key in ["spatial_ref", "crs_wkt"]:
                if key in attrs:
                    try:
                        crs = CRS.from_string(attrs[key])
                    except Exception:
                        pass
        if crs is None:
            warnings.warn(f"Could not find CRS in {path.name}; assuming EPSG:4326.")
            crs = CRS.from_epsg(4326)

        return arr, crs, transform

    raise RuntimeError(f"Could not georeference Hungarian NetCDF file: {path}")


def read_any_radar_raster(path):
    path = Path(path)
    low = path.name.lower()
    if low.endswith(".nc") or low.endswith(".nc4") or low.endswith(".cdf"):
        return read_hu_netcdf_raster(path)
    return read_odim_hdf_raster(path)


# =========================
# REPROJECT / MERGE / PNG
# =========================

def clean_radar_array(arr):
    arr = arr.astype("float32", copy=True)
    arr[arr > 80] = np.nan
    arr[arr < 0] = np.nan
    return arr


def radar_colormap():
    bounds = [-10, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 75]
    colors = [
        "#00000000",
        "#001a66", "#004dff", "#00bfff",
        "#00cc66", "#33ff33",
        "#ffff00", "#ffcc00", "#ff9900",
        "#ff0000", "#cc0000",
        "#9900cc", "#ff00ff",
        "#ffffff", "#ffccff",
    ]
    return ListedColormap(colors), BoundaryNorm(bounds, len(colors))


def write_reprojected(src_arr, src_crs, src_transform, out_tif, dst_epsg=3857, resolution=1000):
    src_arr = clean_radar_array(src_arr)

    height, width = src_arr.shape
    left, bottom, right, top = rasterio.transform.array_bounds(height, width, src_transform)

    dst_crs = CRS.from_epsg(dst_epsg)
    dst_transform, dst_width, dst_height = calculate_default_transform(
        src_crs, dst_crs, width, height, left, bottom, right, top, resolution=resolution
    )

    dst = np.full((dst_height, dst_width), np.nan, dtype="float32")

    reproject(
        source=src_arr,
        destination=dst,
        src_transform=src_transform,
        src_crs=src_crs,
        src_nodata=np.nan,
        dst_transform=dst_transform,
        dst_crs=dst_crs,
        dst_nodata=np.nan,
        resampling=Resampling.nearest,
    )

    profile = {
        "driver": "GTiff",
        "height": dst_height,
        "width": dst_width,
        "count": 1,
        "dtype": "float32",
        "crs": dst_crs,
        "transform": dst_transform,
        "nodata": np.nan,
        "compress": "deflate",
        "predictor": 2,
    }

    with rasterio.open(out_tif, "w", **profile) as ds:
        ds.write(dst, 1)

    return out_tif


def merge_by_max(tif_paths, out_tif):
    srcs = [rasterio.open(p) for p in tif_paths]
    try:
        mosaic, out_transform = merge(srcs, method="first", nodata=np.nan)
        base_profile = srcs[0].profile.copy()
        base_profile.update({
            "height": mosaic.shape[1],
            "width": mosaic.shape[2],
            "transform": out_transform,
            "nodata": np.nan,
            "compress": "deflate",
            "predictor": 2,
        })

        stack = []
        for src in srcs:
            tmp = np.full((mosaic.shape[1], mosaic.shape[2]), np.nan, dtype="float32")
            reproject(
                source=rasterio.band(src, 1),
                destination=tmp,
                src_transform=src.transform,
                src_crs=src.crs,
                src_nodata=np.nan,
                dst_transform=out_transform,
                dst_crs=srcs[0].crs,
                dst_nodata=np.nan,
                resampling=Resampling.nearest,
            )
            stack.append(tmp)

        merged = np.nanmax(np.stack(stack, axis=0), axis=0).astype("float32")

        with rasterio.open(out_tif, "w", **base_profile) as dst:
            dst.write(merged, 1)

    finally:
        for s in srcs:
            s.close()

    return out_tif


def save_transparent_png_and_bounds(tif_path, out_png, bounds_json):
    with rasterio.open(tif_path) as src:
        arr = clean_radar_array(src.read(1))
        b = src.bounds
        transformer = Transformer.from_crs(src.crs, "EPSG:4326", always_xy=True)
        west, south = transformer.transform(b.left, b.bottom)
        east, north = transformer.transform(b.right, b.top)

    cmap, norm = radar_colormap()
    masked = np.ma.masked_invalid(arr)

    # Exact raster aspect ratio. Keep pixels sharp and unblurred.
    h, w = arr.shape
    fig_w = max(8, min(16, w / 120))
    fig_h = fig_w * h / w
    fig = plt.figure(figsize=(fig_w, fig_h), dpi=120)
    ax = fig.add_axes([0, 0, 1, 1])
    ax.imshow(masked, cmap=cmap, norm=norm, interpolation="nearest", origin="upper")
    ax.set_axis_off()
    fig.savefig(out_png, transparent=True, pad_inches=0)
    plt.close(fig)

    info = {
        "bounds": [[south, west], [north, east]],
        "west": west,
        "south": south,
        "east": east,
        "north": north
    }
    with open(bounds_json, "w", encoding="utf-8") as f:
        json.dump(info, f, indent=2)

    return info


# =========================
# COMPOSITE PROCESSING ONLY
# =========================

def process_frame(frame_set):
    main_ts = frame_set["main_ts"]
    print(f"\nProcessing radar frame {main_ts}")
    print(frame_set)

    frame_png = FRAME_DIR / f"radar_{main_ts}.png"
    bounds_file = FRAME_DIR / f"radar_{main_ts}.bounds.json"
    merged_tif = FRAME_DIR / f"radar_{main_ts}_merged_3857.tif"

    if frame_png.exists() and bounds_file.exists():
        print("Frame already processed.")
        with open(bounds_file, "r", encoding="utf-8") as f:
            bounds = json.load(f)["bounds"]
        return {
            "timestamp": main_ts,
            "iso": frame_set["iso"],
            "png": f"radar_frames/radar_{main_ts}.png",
            "bounds": bounds,
            "sources": frame_set
        }

    source_specs = [
        ("cz", frame_set["cz_ts"], None),
        ("sk", frame_set["sk_ts"], None),
        ("de", frame_set["de_ts"], None),
    ]

    if frame_set.get("hu_ts") and frame_set.get("hu_href"):
        source_specs.append(("hu", frame_set["hu_ts"], frame_set["hu_href"]))
    else:
        print("Hungarian frame not available for this timestamp; continuing with CZ/SK/DE.")

    temp_dir = FRAME_DIR / f"_tmp_{main_ts}"
    if temp_dir.exists():
        shutil.rmtree(temp_dir)
    temp_dir.mkdir(parents=True, exist_ok=True)

    try:
        tifs = []
        for kind, ts, href in source_specs:
            try:
                file_path = download_source(kind, ts, href=href)
                arr, crs, transform = read_any_radar_raster(file_path)
                out_tif = temp_dir / f"{kind}_{main_ts}_3857.tif"
                write_reprojected(arr, crs, transform, out_tif, TARGET_EPSG, TARGET_RESOLUTION_METERS)
                tifs.append(out_tif)
                print(f"Added {kind.upper()} radar.")
            except Exception as e:
                if kind == "hu" and HU_OPTIONAL:
                    print(f"Hungarian radar failed, continuing without it: {e}")
                    continue
                raise

        merge_by_max(tifs, merged_tif)
        info = save_transparent_png_and_bounds(merged_tif, frame_png, bounds_file)

    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)

    return {
        "timestamp": main_ts,
        "iso": frame_set["iso"],
        "png": f"radar_frames/radar_{main_ts}.png",
        "bounds": info["bounds"],
        "sources": frame_set
    }


def load_index():
    index_file = OUT_DIR / "radar_index.json"
    if not index_file.exists():
        return {"updated_at": None, "frames": []}
    try:
        return json.loads(index_file.read_text(encoding="utf-8"))
    except Exception:
        return {"updated_at": None, "frames": []}


def save_index(index):
    index["updated_at"] = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    index_file = OUT_DIR / "radar_index.json"
    tmp = index_file.with_suffix(".json.part")
    tmp.write_text(json.dumps(index, indent=2), encoding="utf-8")
    tmp.replace(index_file)


def update_once():
    ensure_dirs()
    frame_set = find_latest_frame_set()
    frame = process_frame(frame_set)

    index = load_index()
    frames = index.get("frames", [])

    frames = [f for f in frames if f.get("timestamp") != frame["timestamp"]]
    frames.append(frame)
    frames = sorted(frames, key=lambda f: f["timestamp"])[-MAX_FRAMES_ON_HTML_SLIDER:]

    index["frames"] = frames
    save_index(index)

    print(f"Composite index updated with {len(frames)} frame(s). Latest: {frame['timestamp']}")

def loop():
    ensure_dirs()
    print("CESTOF composite radar CZ/SK/DE/HU started.")
    print(f"Refresh interval: {INTERVAL_SECONDS} seconds")
    print(f"Output folder: {OUT_DIR.resolve()}")

    while True:
        try:
            update_once()
        except Exception as e:
            print("ERROR:", repr(e))
        time.sleep(INTERVAL_SECONDS)


if __name__ == "__main__":
    import os
    if os.environ.get("RUN_ONCE", "").strip().lower() in ("1", "true", "yes", "y"):
        update_once()
    else:
        loop()
